# Generated by Django 5.2 — index rename + field cleanup for Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0015_auto_20180926_1206'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signaldeferreddispatch',
            new_name='dbmail_sign_eta_bd53d1_idx',
            old_name='dbmail_signaldeferr_eta_done_idx',
        ),
        migrations.AlterField(
            model_name='signaldeferreddispatch',
            name='done',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
